name: cd

on:
  workflow_dispatch:

jobs:
  download:
    name: Download artifact
    runs-on: ubuntu-latest
    steps:  
      - name: Download Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'artifact'
          
      - name: Download Artifact1
        uses: actions/upload-artifact@v3
        with:
          name: 'artifact1'
