name: cd

on:
  workflow_dispatch:

jobs:
  download:
    name: Download artifact
    runs-on: ubuntu-latest
    steps:  
      - name: Find artifacts
        run: |
             cd /
             find . -name artifact
             find . -name artifact1
