name: ci

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
            
      - name: Publish Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: 'artifact1'
          path: target/examplesRepo-0.0.1-SNAPSHOT.jar
          
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact1
